// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/m1thrandir225/imperium/apps/host/internal/programs (interfaces: RAWGIntegration)
//
// Generated by this command:
//
//	mockgen -package mockprograms -destination internal/programs/mocks/rawg_client.go github.com/m1thrandir225/imperium/apps/host/internal/programs RAWGIntegration
//

// Package mockprograms is a generated GoMock package.
package mockprograms

import (
	reflect "reflect"

	programs "github.com/m1thrandir225/imperium/apps/host/internal/programs"
	gomock "go.uber.org/mock/gomock"
)

// MockRAWGIntegration is a mock of RAWGIntegration interface.
type MockRAWGIntegration struct {
	ctrl     *gomock.Controller
	recorder *MockRAWGIntegrationMockRecorder
	isgomock struct{}
}

// MockRAWGIntegrationMockRecorder is the mock recorder for MockRAWGIntegration.
type MockRAWGIntegrationMockRecorder struct {
	mock *MockRAWGIntegration
}

// NewMockRAWGIntegration creates a new mock instance.
func NewMockRAWGIntegration(ctrl *gomock.Controller) *MockRAWGIntegration {
	mock := &MockRAWGIntegration{ctrl: ctrl}
	mock.recorder = &MockRAWGIntegrationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRAWGIntegration) EXPECT() *MockRAWGIntegrationMockRecorder {
	return m.recorder
}

// SearchGame mocks base method.
func (m *MockRAWGIntegration) SearchGame(query string) ([]programs.RAWGGame, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchGame", query)
	ret0, _ := ret[0].([]programs.RAWGGame)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchGame indicates an expected call of SearchGame.
func (mr *MockRAWGIntegrationMockRecorder) SearchGame(query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchGame", reflect.TypeOf((*MockRAWGIntegration)(nil).SearchGame), query)
}
