root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/client ./cmd"
bin = "tmp/client"
full_bin = "./tmp/client"
include_ext = ["go"]
exclude_dir = ["tmp", "webui", "node_modules"]
include_dir = ["."]
log = "air-build.log"
delay = 1000

[log]
time = true