// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/m1thrandir225/imperium/apps/host/pkg/rawg (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -package mockrawg -destination pkg/rawg/mocks/client.go github.com/m1thrandir225/imperium/apps/host/pkg/rawg Client
//

// Package mockrawg is a generated GoMock package.
package mockrawg

import (
	reflect "reflect"

	rawg "github.com/m1thrandir225/imperium/apps/host/pkg/rawg"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// SearchGame mocks base method.
func (m *MockClient) SearchGame(query string) ([]rawg.RAWGGame, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchGame", query)
	ret0, _ := ret[0].([]rawg.RAWGGame)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchGame indicates an expected call of SearchGame.
func (mr *MockClientMockRecorder) SearchGame(query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchGame", reflect.TypeOf((*MockClient)(nil).SearchGame), query)
}
