// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/m1thrandir225/imperium/apps/client/internal/server/ (interfaces: HostHandler)
//
// Generated by this command:
//
//	mockgen -package mockserver -destination internal/server/mocks/host_handler.go github.com/m1thrandir225/imperium/apps/client/internal/server/ HostHandler
//

// Package mockserver is a generated GoMock package.
package mockserver

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockHostHandler is a mock of HostHandler interface.
type MockHostHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHostHandlerMockRecorder
	isgomock struct{}
}

// MockHostHandlerMockRecorder is the mock recorder for MockHostHandler.
type MockHostHandlerMockRecorder struct {
	mock *MockHostHandler
}

// NewMockHostHandler creates a new mock instance.
func NewMockHostHandler(ctrl *gomock.Controller) *MockHostHandler {
	mock := &MockHostHandler{ctrl: ctrl}
	mock.recorder = &MockHostHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHostHandler) EXPECT() *MockHostHandlerMockRecorder {
	return m.recorder
}

// GetHost mocks base method.
func (m *MockHostHandler) GetHost(ctx *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetHost", ctx)
}

// GetHost indicates an expected call of GetHost.
func (mr *MockHostHandlerMockRecorder) GetHost(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHost", reflect.TypeOf((*MockHostHandler)(nil).GetHost), ctx)
}

// GetHostPrograms mocks base method.
func (m *MockHostHandler) GetHostPrograms(ctx *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetHostPrograms", ctx)
}

// GetHostPrograms indicates an expected call of GetHostPrograms.
func (mr *MockHostHandlerMockRecorder) GetHostPrograms(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostPrograms", reflect.TypeOf((*MockHostHandler)(nil).GetHostPrograms), ctx)
}

// GetUserHosts mocks base method.
func (m *MockHostHandler) GetUserHosts(ctx *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetUserHosts", ctx)
}

// GetUserHosts indicates an expected call of GetUserHosts.
func (mr *MockHostHandlerMockRecorder) GetUserHosts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserHosts", reflect.TypeOf((*MockHostHandler)(nil).GetUserHosts), ctx)
}
