services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - auth-server-network
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "imperium-auth-server-db"

networks:
  auth-server-network:
    driver: bridge
volumes:
  postgres-data: